apps/dcs/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.conf.urls import include # Используйте include() чтобы добавлять URL из каталога приложения

from apps.dcs.views import views_dcs
from apps.dcs.views import views_report

urlpatterns = [
    url(r'^$', views_dcs.MainIndex, name='MainIndex'),
    url(r'^sensor/$', views_dcs.SensorList, name='SensorList'),
    url(r'sensor_ajax/$', views_dcs.sensor_ajax, name='sensor_ajax'),
    url(r'ajax/$', views_dcs.get_ajax, name='get_ajax'),
    url(r'^report/$', views_report.report_list, name='report_list'),
    
    ]

mfss/urls.py
# -*- coding: utf-8 -*-
from django.contrib import admin
from django.conf.urls import url
from django.conf.urls import include # Используйте include() чтобы добавлять URL из каталога приложения
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings
from . import views



urlpatterns = [

    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/img/favicon.ico'), name='favicon'),
    url(r'^$', RedirectView.as_view(url='/main/', permanent=True)), #Перенаправляет все запросы 
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('apps.main.urls')),
    url(r'^acs/', include('apps.acs.urls')),
    url(r'^fps/', include('apps.fps.urls')),
    url(r'^dcs/', include('apps.dcs.urls')),
    url(r'^eps/', include('apps.eps.urls')),
    url(r'^fp/', include('apps.fp.urls')),
    url(r'^ktp/', include('apps.ktp.urls')),
    url(r'^scada/', include('apps.scada.urls')),
    url(r'^block/', include('apps.block.urls')),
    url(r'^management/', include('apps.management.urls')),
    url(r'^api/v1/', include('api.v1.urls')),

    url(r'^accounts/logout/', views.user_logout, name='user_logout'),
    url(r'^accounts/', views.user_login, name='user_login'),

    url('bot/', include('tgbot.urls')),
]

urlpatterns += static(settings.DOWNLOAD_URL, document_root=settings.DOWNLOAD_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/dcs/models/model_indicators.py
# -*- coding: utf-8 -*-
from datetime import datetime

from django.db import models
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
from .model_sensor import DcsSensor

class DcsIndicators(models.Model):  # Показания датчиков
    """
    Модель справочника датчиков
    """
    date_time = models.DateTimeField(auto_now=False,
        auto_now_add=False,
        blank=True,
        verbose_name="Время показаний")
    sensor = models.ForeignKey(DcsSensor,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="Датчики")
    value = models.FloatField(default=0.0,
        help_text="",
        verbose_name="Показание")

    def getId(self):
        return self.id

    def __str__(self):
        return self.sensor.name

    class Meta:   # отображение в админики
        ordering = ('sensor',)
        verbose_name = u'показание датчика'
        verbose_name_plural = u'показания датчиков'
        indexes = [models.Index(fields=['date_time','sensor',]),]

apps/dcs/forms/form_dsc_sensor.py
# -*- coding: utf-8 -*-
from django import forms
from apps.dcs.models.model_sensor import DcsSensor
from apps.main.models.model_datamfsb import DataMfsb

class DcsSensorForm(forms.ModelForm):
    critical_type_list = (
        ('max', 'Максимальный'),
        ('min', 'Минимальный'),
    )
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','autofocus':'','placeholder':'Наименование'})) 
    critical_value = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','type':'number','step':'0.1','autofocus':'',})) 
    ratio = forms.FloatField(widget=forms.TextInput(attrs={'class':'form-control','type':'number','step':'0.1','autofocus':'',})) 
    max_value = forms.FloatField(widget=forms.TextInput(attrs={'class':'form-control','type':'number','step':'0.1','autofocus':'',})) 
    critical_type = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class':'form-control select2',
                'autofocus':''}),
        choices=critical_type_list)
    #value = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','type':'number','step':'0.00001','autofocus':'',})) 
    active=forms.BooleanField(widget=forms.CheckboxInput(),required = False)
    unit= forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','autofocus':'','placeholder':'Единица измерения'})) 
    comments = forms.CharField(required=False,widget=forms.Textarea(attrs={'class':'form-control','autofocus':'','placeholder':'Комментарий'})) 
    scale= forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','autofocus':'','placeholder':'Шкала датчика'})) 
    norm_value_from = forms.FloatField(widget=forms.TextInput(attrs={'class':'form-control','type':'number','step':'0.1','autofocus':'',})) 
    norm_value_to = forms.FloatField(widget=forms.TextInput(attrs={'class':'form-control','type':'number','step':'0.1','autofocus':'',})) 
    danger_value_from = forms.FloatField(widget=forms.TextInput(attrs={'class':'form-control','type':'number','step':'0.1','autofocus':'',})) 
    danger_value_to = forms.FloatField(widget=forms.TextInput(attrs={'class':'form-control','type':'number','step':'0.1','autofocus':'',})) 
    critical_value_from = forms.FloatField(widget=forms.TextInput(attrs={'class':'form-control','type':'number','step':'0.1','autofocus':'',})) 
    critical_value_to = forms.FloatField(widget=forms.TextInput(attrs={'class':'form-control','type':'number','step':'0.1','autofocus':'',})) 

    class Meta:
        model=DcsSensor
        fields = ('id','tag','name','critical_value',
                  'critical_type','value','active',
                  'unit','max_value','comments',
                  'ratio','scale','norm_value_from',
                  'norm_value_to','danger_value_from',
                  'danger_value_to','critical_value_from',
                  'critical_value_to',)

apps/dcs/views/views_dcs.py
# -*- coding: utf-8 -*-
import traceback
import requests

from datetime import datetime,timedelta
from requests.auth import HTTPBasicAuth
from django.conf import settings
from django.db.models import Q
from django.shortcuts import render
from django.http import HttpResponse
from django.conf import settings
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.db.models import Avg, Max, Min


from apps.dcs.models.model_indicators import DcsIndicators
from apps.dcs.models.model_sensor import DcsSensor


from apps.util import generalmodule
from sabron.util import logging

def float_range(A, L=None, D=None):
    #Use float number in range() function
    # if L and D argument is null set A=0.0 and D = 1.0
    if L == None:
        L = A + 0.0
        A = 0.0
    if D == None:
        D = 1.0
    while True:
        if D > 0 and A >= L:
            break
        elif D < 0 and A <= L:
            break
        yield ("%g" % A) # return float number
        A = A + D
#end of function float_range()

def get_ajax(request):
    try:
        if request.method == "POST":
            sensor_list = DcsSensor.objects.filter(active=True).all().order_by('name')
            m_sensor = []
            for sensor in sensor_list:
                sensor_dict = dict()
                sensor_dict.update(sensor_id=sensor.id)
                sensor_dict.update(value=sensor.value / sensor.ratio)
                sensor_dict.update(critical_value=sensor.critical_value)
                sensor_dict.update(unit=sensor.unit)
                pecent = ((sensor.value / sensor.ratio) * 100) / sensor.critical_value
                sensor_dict.update(pecent_value=pecent)
                #sensor.critical_value
                #color=0 зеленый
                #color=1 желтый
                #color=2 красный
                color = 'bg-success'
                if sensor.critical_type == 'max':
                    if sensor.value / sensor.ratio >= sensor.critical_value:
                        color = 'bg-danger'
                else:
                    if sensor.value / sensor.ratio <= sensor.critical_value:
                        color = 'bg-danger'
                sensor_dict.update(color=color)
                m_sensor.append(sensor_dict)
            return generalmodule.ReturnJson(200,m_sensor)
    except Exception as err:
        logging.error(traceback.format_exc())
        data = dict()
        data.update(status=-1)
        return generalmodule.ReturnJson(200,data)

def MainIndexDefault(request):
     if request.method == "GET":
        sensor_list = DcsSensor.objects.filter(active=True).all().order_by('name')
        m_sensor = []
        for sensor in sensor_list:
            if sensor.ratio == 0:
                ratio = 1
            else:
                ratio = sensor.ratio
            str_value=str(sensor.value / ratio).replace(',','.')
            sensor_dict = dict()
            sensor_dict.update(sensor=sensor)

            sensor_dict.update(value=sensor.value / ratio)
            sensor_dict.update(str_value=str_value)
            sensor_dict.update(critical_value=sensor.critical_value)
            sensor_dict.update(str_critical_value=str(sensor.critical_value).replace(',','.'))
            sensor_dict.update(unit=sensor.unit)
            sensor_dict.update(scale=sensor.scale)
            sensor_dict.update(norm_value_from=str(sensor.norm_value_from).replace(',','.'))
            sensor_dict.update(norm_value_to=str(sensor.norm_value_to).replace(',','.'))
            sensor_dict.update(danger_value_from=str(sensor.danger_value_from).replace(',','.'))
            sensor_dict.update(danger_value_to=str(sensor.danger_value_to).replace(',','.'))
            sensor_dict.update(critical_value_from=str(sensor.critical_value_from).replace(',','.'))
            sensor_dict.update(critical_value_to=str(sensor.critical_value_to).replace(',','.'))
            #sensor.critical_value
            #color=0 зеленый
            #color=1 желтый
            #color=2 красный
            color = 'bg-success'
            if sensor.critical_type == 'max':
                if sensor.value / ratio >= sensor.critical_value:
                    color = 'bg-danger'
            else:
                if sensor.value / ratio <= sensor.critical_value:
                    color = 'bg-danger'
            sensor_dict.update(color=color)
            m_sensor.append(sensor_dict)
        context = {
              'updatepage':True,
              'sensor_list':sensor_list,
              'm_sensor':m_sensor,
                }
        return render(request, 'dcs_main.html',context) 


@login_required(login_url='/accounts/login/?next=')
@never_cache
def SensorList(request):
    try:
        if request.method == "GET":
            param = request.GET.dict()
            sensor = DcsSensor.objects.filter(id=param['id']).first()
            now = datetime.now()
            start_date = now - timedelta(hours=0, minutes=0)
            sensor_list = DcsIndicators.objects.filter(sensor=sensor).filter(date_time__range=[start_date, datetime.now()]).all().order_by('-date_time')
            sensor_str = ''
            for sensor_in in sensor_list:
                sensor_str = sensor_str+str(sensor_in.value).replace(',','.')+','
            context = {
                    'sensor':sensor,
                    'sensor_list':sensor_list,
                    'sensor_str':sensor_str,
                    }
            return render(request, 'dcs_sensor_list.html',context) 
    except Exception as err:
        logging.error(traceback.format_exc())

@login_required(login_url='/accounts/login/?next=')
@never_cache
def sensor_ajax(request):
    try:
        if request.method == "GET":
            sensor_dict = dict()
            param = request.GET.dict()
            sensor = DcsSensor.objects.filter(id=param['id']).first()
            strftime = "%H:%M:%S"
            if param['sensor_type'] == 'sec':
                strftime = "%H:%M:%S"
                sensor_list = DcsIndicators.objects.filter(sensor=sensor).order_by('-date_time')[:100]
                #sensor_list = AcsIndicators.objects.filter(sensor=sensor).annotate(
                #        date_value=TruncSecond('date_time')).values('date_time', 'date_value', 'value', 'sensor__ratio').order_by('-date_value').distinct('date_value')[:30]
            elif param['sensor_type'] == 'min':
                strftime = "%H:%M"
                sensor_list = DcsIndicators.objects.filter(sensor=sensor).order_by('-date_time')[:3600]
                #sensor_list = AcsIndicators.objects.filter(sensor=sensor).annotate(
                #        date_value=TruncMinute('date_time')).values('date_time','date_value', 'value', 'sensor__ratio').order_by('-date_value').distinct('date_value')[:30]
            else:
                strftime = "%H:00"
                sensor_list = DcsIndicators.objects.filter(sensor=sensor).order_by('-date_time')[:120000]
                #sensor_list = AcsIndicators.objects.filter(sensor=sensor).annotate(
                #        date_value=TruncHour('date_time')).values('date_value', 'date_value','value', 'sensor__ratio').order_by('-date_value').distinct('date_value')[:30]
                #sensor_list = AcsIndicators.objects.filter(sensor=sensor).order_by('-date_time')
                #m_sensor = []
                #data_list =list()
                #count = 0
                #for sensor in sensor_list:
                    #logging.message(sensor)
                #    data = sensor.date_time.strftime(strftime)
                #    if data in data_list:
                #        continue;
                #    data_list.append(data)
                #    sensor_dict = dict()
                #    sensor_dict.update(date_time=sensor.date_time.strftime(strftime))
                    #sensor_dict.update(date_time=sensor['date_value'].strftime("%d-%m %H:%M:%S"))
                #    sensor_dict.update(value=sensor.value / sensor.sensor.ratio)
                #    m_sensor.append(sensor_dict)
                #    count = count+1
                #    if count > 30:
                #        return generalmodule.ReturnJson(200,m_sensor) 
                #return generalmodule.ReturnJson(200,m_sensor)
            
            m_sensor = []
            data_list =list()
            count = 0
            for sensor in sensor_list:
                #logging.message(sensor)
                data = sensor.date_time.strftime(strftime)
                if data in data_list:
                    continue;
                data_list.append(data)
                sensor_dict = dict()
                sensor_dict.update(date_time=sensor.date_time.strftime(strftime))
                #sensor_dict.update(date_time=sensor['date_value'].strftime("%d-%m %H:%M:%S"))
                sensor_dict.update(value=sensor.value / sensor.sensor.ratio)
                m_sensor.append(sensor_dict)
                count = count+1
                if count > 30:
                    return generalmodule.ReturnJson(200,m_sensor) 
            return generalmodule.ReturnJson(200,m_sensor) 
    except Exception as err:
        logging.error(traceback.format_exc())



@login_required(login_url='/accounts/login/?next=')
@never_cache
def MainIndex(request):
    try:
        #if request.user.profile.role == 2: # Администратор системы
        #    return redirect('/management/')

        return MainIndexDefault(request)
    except Exception as err:
        logging.error(traceback.format_exc())
 

apps/dcs/templates/report/dcs_repor_error.html
{% extends "dcs_default.html" %}
{% load static %}
{% load mysettings %}


{% block header_link %}
<link type="text/css" rel="stylesheet" href="{% static '/css/speedometer.css' %}?ver={% settings_value 'APP_VER' %}">
<!-- daterange picker -->
<link rel="stylesheet" href="{% static 'lte/plugins/daterangepicker/daterangepicker.css' %}?ver={% settings_value 'APP_VER' %}">
<!-- Select2 -->
<link rel="stylesheet" href="{% static 'lte/plugins/select2/css/select2.min.css' %}?ver={% settings_value 'APP_VER' %}">
<link rel="stylesheet" href="{% static 'lte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}?ver={% settings_value 'APP_VER' %}">


{% endblock header_link %}

{% block info_title %}
<h5>Контроль запыленности : Отчеты</h5>
{% endblock info_title %}

{% block content %}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 id="sensorname">Срабатывание датчиков</h1>
                <h6 id="maxdate" style="color:darkcyan"></h6>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/acs/report/">Главная</a></li>
                    <li class="breadcrumb-item active">Срабатывание датчиков</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="containe col-sm-8">
        <form class="form-horizontal">
            {% csrf_token %}
                <div id="card_param" class="card card-primary card-outline card-tabs">
                        <div class="card-header p-0 pt-1 border-bottom-0">
                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                            </div>
                        </div>
                <div class="card-body">
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Начальная дата:</label>
                        <div class="input-group date col-sm-4" id="datestart" data-target-input="nearest">
                            <input id="id_datestart" type="text" class="form-control datetimepicker-input" data-target="#datestart">
                            <div class="input-group-append" data-target="#datestart" data-toggle="datetimepicker">
                                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Конечная дата :</label>
                        <div class="input-group date col-sm-4" id="datestop" data-target-input="nearest">
                            <input id="id_datestop" type="text" class="form-control datetimepicker-input" data-target="#datestop">
                            <div class="input-group-append" data-target="#datestop" data-toggle="datetimepicker">
                                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_sensor" class="col-sm-2 col-form-label">Датчик:</label>
                        <div class="col-sm-8">
                            <select name="sensor" class="form-control select2" style="width: 100%;" id="id_sensor">
                                {% for data in sensor_list  %}
                                <option value="{{data.id}}">{{data.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <a type="button" onclick="reportshow()" class="btn btn-success">Сформировать</a>
                    <a type="button" onclick="cancel()" class="btn btn-default float-right">Закрыть</a>
                </div>                <!-- /.card -->
            </div>
        </form>
    </div>
    <div id="print_Panel" class="container-fluid" style="height:100px;">
        <div id="reportPanel" class="card card-primary card-outline card-tabs">
            <div class="card-header p-1 pt-1 ">
                <div class="dt-buttons btn-group flex-wrap">
                    <!--<button class="btn btn-secondary buttons-excel buttons-html5" tabindex="0" aria-controls="example1" type="button"><span>Excel</span></button>
                    <button class="btn btn-secondary buttons-pdf buttons-html5" tabindex="0" aria-controls="example1" type="button"><span>PDF</span></button>
                    <a class="btn btn-secondary buttons-print" onClick="javascript:CallPrint('print_Panel');" tabindex="0" aria-controls="example1" type="button"><span>Печать</span></a>-->
                </div>
            </div>
            <div id="reportPanelBody" class="card-body">
                <div class="alert alert-warning alert-dismissible" style="max-width:450px;">
                    <!--<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>-->
                    <h5><i class="icon fas fa-exclamation-triangle"></i> </h5>
                    Отчет не сформирован. Нажмите "Сформировать" для получения отчета
                </div>
            </div>
            <!-- /.card -->
        </div>
    </div>


</section>


{% endblock %}

{% block script_footer %}
<script src="{% static 'js/gauge.min.js' %}?ver={% settings_value 'APP_VER' %}"></script>
<script src="{% static 'js/speedometer.js' %}?ver={% settings_value 'APP_VER' %}"></script>
<!-- date-range-picker -->
<script src="{% static 'lte/plugins/daterangepicker/daterangepicker.js' %}?ver={% settings_value 'APP_VER' %}"></script>
<script>
    $(function () {
        $('.date').datetimepicker({
            locale: 'ru',
            format: 'L',
            format: 'DD.MM.YYYY',
            autoclose: true,
        });
        //Initialize Select2 Elements
        $('.select2').select2({
            theme: 'bootstrap4'
        })

    });
    function reportshow() {
        var DataStart = $("#id_datestart").val();
        var DataStop = $("#id_datestop").val();
		var id_sensor = $("#id_sensor").select2('data');
		if (DataStart.trim() == "") {
			$("#id_datestart").css('border', "3px solid #e42121").focus();
			return false;
		} else {
			$("#id_datestart").css('border', "1px solid rgb(206, 212, 218)");
		}
        if (DataStop.trim() == "") {
             $("#id_datestop").css('border', "3px solid #e42121").focus();
             return false;
		} else {
			$("#id_datestop").css('border', "1px solid rgb(206, 212, 218)");
		}

		if (id_sensor.length == 0) {
			$("#id_sensor").css('border', "3px solid #e42121").focus();
			return false;
		} else {
			$("#id_sensor").css('border', "1px solid rgb(206, 212, 218)");
		}

        if (!!DataStart)  {
			$("#reportPanelBody").html('<div class="overlay"><i class="fas fa-3x fa-sync-alt fa-spin"></i></div>')
            $.ajax({
                type: 'POST', // метод отправки
				url: window.location.pathname+'?name=reporterror',
                data: {
                    "DataStart": DataStart,
                    "DataStop": DataStop,
                    "metod": 'create',
					"id_sensor": id_sensor[0].id,
                },
				success: function (data) {
                    $('#card_param').CardWidget('collapse')
                    document.getElementById('reportPanel').style.height = '';
                    $("#reportPanelBody").html(data); // при успешном получении ответа от сервера, заносим полученные данные в элемент с классом answer
                },
                error: function (dataerr) {
                    $("#reportPanelBody").html(dataerr); // при успешном получении ответа от сервера, заносим полученные данные в элемент с классом answer

                },
				timeout: 60000 // sets timeout to 3 seconds
            });

        }

    }
    function cancel() {
        document.location.href = "./";
    }

    function CallPrint(strid) {
        var prtContent = document.getElementById(strid);
        var WinPrint = window.open('', '', 'left=50,top=50,width=800,height=640,toolbar=0,scrollbars=1,status=0');
        WinPrint.document.write('');
        WinPrint.document.write(prtContent.innerHTML);
        WinPrint.document.write('');
        WinPrint.document.close();
        WinPrint.focus();
        WinPrint.print();
        WinPrint.close();
        prtContent.innerHTML = strOldOne;
    }

</script>
{% endblock script_footer %}