apps/block/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.conf.urls import include # Используйте include() чтобы добавлять URL из каталога приложения

from apps.block.views import views_block
from apps.block.views import views_report

urlpatterns = [
    url(r'^$', views_block.MainIndex, name='MainIndex'),
    url(r'^sensor/$', views_block.SensorList, name='SensorList'),
    url(r'sensor_ajax/$', views_block.sensor_ajax, name='sensor_ajax'),
    url(r'ajax/$', views_block.get_ajax, name='get_ajax'),
    url(r'^report/$', views_report.report_list, name='SensorList'),
    
    
    ]

mfss/urls.py
# -*- coding: utf-8 -*-
from django.contrib import admin
from django.conf.urls import url
from django.conf.urls import include # Используйте include() чтобы добавлять URL из каталога приложения
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings
from . import views



urlpatterns = [

    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/img/favicon.ico'), name='favicon'),
    url(r'^$', RedirectView.as_view(url='/main/', permanent=True)), #Перенаправляет все запросы 
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('apps.main.urls')),
    url(r'^acs/', include('apps.acs.urls')),
    url(r'^fps/', include('apps.fps.urls')),
    url(r'^dcs/', include('apps.dcs.urls')),
    url(r'^eps/', include('apps.eps.urls')),
    url(r'^fp/', include('apps.fp.urls')),
    url(r'^ktp/', include('apps.ktp.urls')),
    url(r'^scada/', include('apps.scada.urls')),
    url(r'^block/', include('apps.block.urls')),
    url(r'^management/', include('apps.management.urls')),
    url(r'^api/v1/', include('api.v1.urls')),

    url(r'^accounts/logout/', views.user_logout, name='user_logout'),
    url(r'^accounts/', views.user_login, name='user_login'),

    url('bot/', include('tgbot.urls')),
]

urlpatterns += static(settings.DOWNLOAD_URL, document_root=settings.DOWNLOAD_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/block/models/model_block.py
from django.db import models


class Block(models.Model):
    name = models.CharField(db_column='Name', max_length=150, blank=True, null=True)  # Field name made lowercase.
    values = models.FloatField(db_column='Values', blank=True, null=True)  # Field name made lowercase.
    date = models.DateTimeField(db_column='Date', blank=True, null=True)  # Field name made lowercase.
    check = models.BooleanField(db_column='Check', blank=True, null=True,default=False)  # Field name made lowercase.

    class Meta:
        verbose_name = u'Блокировки'
        

apps/block/models/model_indicators.py
# -*- coding: utf-8 -*-
from datetime import datetime

from django.db import models
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
from .model_sensor import BlockSensor

class BlockIndicators(models.Model):  # Показания блокировок
    type_list = (
        (0, 'нет связи (блокировка выведена)'),
        (1, 'блокировка активна'),
    )
     
    date_time = models.DateTimeField(auto_now=False,
        auto_now_add=False,
        blank=True,
        verbose_name="Время показаний")
    sensor = models.ForeignKey(BlockSensor,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="Датчик")
    value = models.IntegerField(choices=type_list,
           blank=True,
           default=0,
           verbose_name="Активность") 
    

    def getId(self):
        return self.id

    def __str__(self):
        return self.sensor.name

    class Meta:   # отображение в админики
        ordering = ('sensor',)
        verbose_name = u'показание датчика'
        verbose_name_plural = u'показания датчиков'
        indexes = [
            models.Index(fields=['date_time','sensor',]),]

apps/block/models/model_sensor.py
# -*- coding: utf-8 -*-
from datetime import datetime

from django.db import models

from apps.catalog.models.model_zones import Zone

class BlockSensor(models.Model):  
    type_list = (
        (0, 'нет связи (блокировка выведена)'),
        (1, 'блокировка активна'),
    )

    zone = models.ForeignKey(Zone,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Зона")
    tag = models.CharField(max_length=160,
        help_text="",
        default=" ",
        verbose_name="ТЭГ")
    position = models.CharField(max_length=20,
        help_text="",
        default=" ",
        blank = True,
        verbose_name="Позиция")
    name = models.CharField(max_length=160,
        help_text="",
        default=" ",
        verbose_name="Наименование")
    value = models.IntegerField(choices=type_list,
           blank=True,
           default=0,
           verbose_name="Активность") 
    connect_time = models.DateTimeField(
        default=datetime.now,
        blank=True,
        verbose_name="Последнее подключение")
     

    def getId(self):
        return self.id

    def __str__(self):
        return self.name

    class Meta:   # отображение в админики
        ordering = ('name',)
        verbose_name = u'датчик блокировки'
        verbose_name_plural = u'датчики блокировок'
        indexes = [models.Index(fields=['tag',]),
            models.Index(fields=['name',]),
            models.Index(fields=['tag','name',]),]

tgbot/models.py
import requests

from django.db import models
from tgbot import utils

from sabron.util import logging

class User(models.Model):
    user_id = models.BigIntegerField(primary_key=True)
    username = models.CharField(max_length=32, null=True, blank=True)
    first_name = models.CharField(max_length=256)
    last_name = models.CharField(max_length=256, null=True, blank=True)
    language_code = models.CharField(max_length=8, null=True, blank=True, help_text="Telegram client's lang")
    deep_link = models.CharField(max_length=64, null=True, blank=True)

    is_blocked_bot = models.BooleanField(default=False)
    is_banned = models.BooleanField(default=False)

    is_admin = models.BooleanField(default=False)
    is_moderator = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'@{self.username}' if self.username is not None else f'{self.user_id}'

    @classmethod
    def get_user_and_created(cls, update, context):
        """ python-telegram-bot's Update, Context --> User instance """
        data = utils.extract_user_data_from_update(update)
        u, created = cls.objects.update_or_create(user_id=data["user_id"], defaults=data)

        #if created:
        #    if context is not None and context.args is not None and len(context.args) > 0:
        #        payload = context.args[0]
        #        if str(payload).strip() != str(data["user_id"]).strip():  # you can't invite yourself
        #            u.deep_link = payload
        #            u.save()

        return u, created

    @classmethod
    def get_user(cls, update, context):
        u, _ = cls.get_user_and_created(update, context)
        return u

    @classmethod
    def get_user_by_username_or_user_id(cls, string):
        """ Search user in DB, return User or None if not found """
        username = str(string).replace("@", "").strip().lower()
        if username.isdigit():  # user_id
            return cls.objects.filter(user_id=int(username)).first()
        return cls.objects.filter(username__iexact=username).first()

    def invited_users(self):  # --> User queryset 
        return User.objects.filter(deep_link=str(self.user_id), created_at__gt=self.created_at)
    class Meta:   # отображение в админики
        verbose_name = u'пользователь телеграм'
        verbose_name_plural = u'пользователи телеграм'


class Location(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    latitude = models.FloatField()
    longitude = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"user: {self.user}, created at {self.created_at.strftime('(%H:%M, %d %B %Y)')}"

    def save(self, *args, **kwargs):
        super(Location, self).save(*args, **kwargs)
        # Parse location with arcgis
        from .tasks import save_data_from_arcgis
        save_data_from_arcgis.delay(latitude=self.latitude, longitude=self.longitude, location_id=self.pk)


class Arcgis(models.Model):
    location = models.OneToOneField(Location, on_delete=models.CASCADE, primary_key=True)

    match_addr = models.CharField(max_length=200)
    long_label = models.CharField(max_length=200)
    short_label = models.CharField(max_length=128)

    addr_type = models.CharField(max_length=128)
    location_type = models.CharField(max_length=64)
    place_name = models.CharField(max_length=128)

    add_num = models.CharField(max_length=50)
    address = models.CharField(max_length=128)
    block = models.CharField(max_length=128)
    sector = models.CharField(max_length=128)
    neighborhood = models.CharField(max_length=128)
    district = models.CharField(max_length=128)
    city = models.CharField(max_length=64)
    metro_area = models.CharField(max_length=64)
    subregion = models.CharField(max_length=64)
    region = models.CharField(max_length=128)
    territory = models.CharField(max_length=128)
    postal = models.CharField(max_length=128)
    postal_ext = models.CharField(max_length=128)

    country_code = models.CharField(max_length=32)

    lng = models.DecimalField(max_digits=21, decimal_places=18)
    lat = models.DecimalField(max_digits=21, decimal_places=18)

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.location}, city: {self.city}, country_code: {self.country_code}"

    @classmethod
    def from_json(cls, j, location_id):
        a = j.get("address")
        l = j.get("location")

        if "address" not in j or "location" not in j:
            return

        arcgis_data = {
            "match_addr": a.get("Match_addr"),
            "long_label": a.get("LongLabel"),
            "short_label": a.get("ShortLabel"),
            "addr_type": a.get("Addr_type"),
            "location_type": a.get("Type"),
            "place_name": a.get("PlaceName"),
            "add_num": a.get("AddNum"),
            "address": a.get("Address"),
            "block": a.get("Block"),
            "sector": a.get("Sector"),
            "neighborhood": a.get("Neighborhood"),
            "district": a.get("District"),
            "city": a.get("City"),
            "metro_area": a.get("MetroArea"),
            "subregion": a.get("Subregion"),
            "region": a.get("Region"),
            "territory": a.get("Territory"),
            "postal": a.get("Postal"),
            "postal_ext": a.get("PostalExt"),
            "country_code": a.get("CountryCode"),
            "lng": l.get("x"),
            "lat": l.get("y")
        }

        arc, _ = cls.objects.update_or_create(location_id=location_id, defaults=arcgis_data)
        return

    @staticmethod
    def reverse_geocode(lat, lng):
        r = requests.post(
            "https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/reverseGeocode",
            params={
                'f': 'json',
                'location': f'{lng}, {lat}',
                'distance': 50000,
                'outSR': '',
            },
            headers={
                'Content-Type': 'application/json',
            }
        )
        return r.json()


class UserActionLog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    action = models.CharField(max_length=128)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"user: {self.user}, made: {self.action}, created at {self.created_at.strftime('(%H:%M, %d %B %Y)')}"

apps/block/templates/block_default.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
{% load mysettings %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="yandex-verification" content="3697ed9bb1a232f1" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta name="Author" content="{% settings_value 'AUTHOR' %}" />
    <meta name="keywords" content="{% settings_value 'KEYWORDS' %}" />
    <meta name="description" content="{% settings_value 'DESCRIPTION' %}" />
    <title>{% settings_value 'SITE_TITLE' %} : {{ user.profile.client }}</title>
    <link rel="icon" href="{% static 'img/favicon.ico' %}?ver={% settings_value 'APP_VER' %}" type="image/x-icon">
<!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'lte/plugins/fontawesome-free/css/all.min.css' %}?ver={% settings_value 'APP_VER' %}">
  <!-- daterange picker -->
  <link rel="stylesheet" href="{% static 'lte/plugins/daterangepicker/daterangepicker.css' %}?ver={% settings_value 'APP_VER' %}">
  <!-- iCheck for checkboxes and radio inputs -->
  <link rel="stylesheet" href="{% static 'lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}?ver={% settings_value 'APP_VER' %}">
  <!-- Bootstrap Color Picker -->
  <link rel="stylesheet" href="{% static 'lte/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css' %}?ver={% settings_value 'APP_VER' %}">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{% static 'lte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}?ver={% settings_value 'APP_VER' %}">
  <!-- Select2 -->
  <link rel="stylesheet" href="{% static 'lte/plugins/select2/css/select2.min.css' %}?ver={% settings_value 'APP_VER' %}">
  <link rel="stylesheet" href="{% static 'lte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}?ver={% settings_value 'APP_VER' %}">
  <!-- Bootstrap4 Duallistbox -->
  <link rel="stylesheet" href="{% static 'lte/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css' %}?ver={% settings_value 'APP_VER' %}">
  <!-- BS Stepper -->
  <link rel="stylesheet" href="{% static 'lte/plugins/bs-stepper/css/bs-stepper.min.css' %}?ver={% settings_value 'APP_VER' %}">
  <!-- dropzonejs -->
  <link rel="stylesheet" href="{% static 'lte/plugins/dropzone/min/dropzone.min.css' %}?ver={% settings_value 'APP_VER' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'lte/dist/css/adminlte.min.css' %}?ver={% settings_value 'APP_VER' %}">   

    {% block header_link %}
    {% endblock header_link %}

</head>
<body class=" layout-fixed text-sm layout-footer-fixed">


    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-light navbar-light navbar-fixed-top text-sm" style='position:sticky; top:0px; left;0;'>
            <ul class="navbar-nav">
                <li class="nav-item">
                    {% block info_title %}

                    {% endblock info_title %}

                </li>
            </ul>    <!-- Right navbar links -->

            <ul class="navbar-nav ml-auto">
                <!-- Messages Dropdown Menu -->

                <li class="nav-item dropdown mr-3 lead">
                    <h6 class="m-1" id="time"></h6>
                </li>

            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-light-maroon">
            <!-- Brand Logo -->
            <a href="/" class="brand-link navbar-light">
                <img src="{% static 'img/login_logo.png' %}?ver={% settings_value 'APP_VER' %}" alt="{% settings_value 'SITE_TITLE' %}" class="brand-image " style="opacity: .8">

                <span class="brand-text font-weight-light">Киберкод</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column text-sm nav-child-indent " data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->

                        <li class="nav-item">
                            <a href="/" class="nav-link">
                                <i class="nav-icon fas fa-table"></i>
                                <p>
                                    Информационный экран
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/block/report/" class="nav-link">
                                <i class="nav-icon fas fa-copy"></i>
                                <p>
                                    Отчеты
                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper text-sm">
            {% block content %}
            {% endblock %}
        </div>


        <!-- /.content-wrapper -->
        <footer class="main-footer text-sm">
            <strong>{% settings_value 'APP_COPPIRIGHT' %} </strong>
            {% settings_value 'AUTHOR' %}
            - {% settings_value 'APP_VEK' %}
            <div class="float-right d-none d-sm-inline-block">
                <b>Версия :</b> {% settings_value 'APP_VER' %}
            </div>
        </footer>

    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
<script src="{% static 'lte/plugins/jquery/jquery.min.js' %}?ver={% settings_value 'APP_VER' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'lte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}?ver={% settings_value 'APP_VER' %}"></script>
<!-- Select2 -->
<script src="{% static 'lte/plugins/select2/js/select2.full.min.js' %}?ver={% settings_value 'APP_VER' %}"></script>
<!-- Bootstrap4 Duallistbox -->
<script src="{% static 'lte/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js' %}?ver={% settings_value 'APP_VER' %}"></script>
<!-- InputMask -->
<script src="{% static 'lte/plugins/moment/moment.min.js' %}?ver={% settings_value 'APP_VER' %}"></script>
<script src="{% static 'lte/plugins/inputmask/jquery.inputmask.min.js' %}?ver={% settings_value 'APP_VER' %}"></script>
<!-- date-range-picker -->
<script src="{% static 'lte/plugins/daterangepicker/daterangepicker.js' %}?ver={% settings_value 'APP_VER' %}"></script>
<!-- bootstrap color picker -->
<script src="{% static 'lte/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js' %}?ver={% settings_value 'APP_VER' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'lte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}?ver={% settings_value 'APP_VER' %}"></script>
<!-- BS-Stepper -->
<script src="{% static 'lte/plugins/bs-stepper/js/bs-stepper.min.js' %}?ver={% settings_value 'APP_VER' %}"></script>
<!-- dropzonejs -->
<script src="{% static 'lte/plugins/dropzone/min/dropzone.min.js' %}?ver={% settings_value 'APP_VER' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'lte/dist/js/adminlte.min.js' %}?ver={% settings_value 'APP_VER' %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.0/moment-with-locales.min.js" integrity="sha512-EATaemfsDRVs6gs1pHbvhc6+rKFGv8+w4Wnxk4LmkC0fzdVoyWb+Xtexfrszd1YuUMBEhucNuorkf8LpFBhj6w==" crossorigin="anonymous"></script>
    
 
    <!-- OPTIONAL SCRIPTS -->
    <script src="{% static 'lte/plugins/chart.js/Chart.min.js' %}?ver={% settings_value 'APP_VER' %}"></script>

    <script src="{% static 'js/main.js' %}?ver={% settings_value 'APP_VER' %}"></script>

    <script>
        function clock() {
    var d = new Date();
    var day = d.getDate();
    var hrs = d.getHours();
    var min = d.getMinutes();
    var sec = d.getSeconds();

    var mnt = new Array("января", "февраля", "марта", "апреля", "мая",
    "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря");

    if (day <= 9) day="0" + day;
    if (hrs <= 9) hrs="0" + hrs;
    if (min <=9 ) min="0" + min;
    if (sec <= 9) sec="0" + sec;

    $("#time").html("Время: " + hrs + ":" + min + ":" + sec + "&nbsp;&nbsp;&nbsp;" +
    day + " " + mnt[d.getMonth()] + " " + d.getFullYear() + " г.");
    }

		$(document).ready(function(){
            clock()
            setInterval("clock()",1000);
		});


    </script>
    {% block script_footer %}


    {% endblock script_footer %}
</body>
</html>

apps/block/templates/block_report.html
{% extends "block_default.html" %}
{% load static %}
{% load mysettings %}


{% block header_link %}
<link type="text/css" rel="stylesheet" href="{% static '/css/speedometer.css' %}?ver={% settings_value 'APP_VER' %}">
<!-- daterange picker -->
<link rel="stylesheet" href="{% static 'lte/plugins/daterangepicker/daterangepicker.css' %}?ver={% settings_value 'APP_VER' %}">
<!-- Select2 -->
<link rel="stylesheet" href="{% static 'lte/plugins/select2/css/select2.min.css' %}?ver={% settings_value 'APP_VER' %}">
<link rel="stylesheet" href="{% static 'lte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}?ver={% settings_value 'APP_VER' %}">


{% endblock header_link %}

{% block info_title %}
<h5>
    Работа блокировок : Отчеты<h5>
        {% endblock info_title %}

        {% block content %}
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <p id="id_time"></p>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <section class="content">
            <div class="containe col-sm-8">
                <form class="form-horizontal">
                    {% csrf_token %}
                    <div class="card card-primary card-outline card-tabs">
                        <div class="card-header p-0 pt-1 border-bottom-0">
                        </div>
                        <div class="card-body">
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Начальная дата:</label>
                                <div class="input-group date col-sm-4" id="datestart" data-target-input="nearest">
                                    <input id="id_datestart" type="text" class="form-control datetimepicker-input" data-target="#datestart">
                                    <div class="input-group-append" data-target="#datestart" data-toggle="datetimepicker">
                                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Конечная дата :</label>
                                <div class="input-group date col-sm-4" id="datestop" data-target-input="nearest">
                                    <input id="id_datestop" type="text" class="form-control datetimepicker-input" data-target="#datestop">
                                    <div class="input-group-append" data-target="#datestop" data-toggle="datetimepicker">
                                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_block" class="col-sm-2 col-form-label">Блокировка:</label>
                                <div class="col-sm-8">
                                    <select name="block" class="form-control select2" style="width: 100%;" id="id_block">
                                        {% for data in block_list  %}
                                        <option value="{{data.id}}">{{data.name}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <a type="button" onclick="reportshow()" class="btn btn-success">Сформировать</a>
                            <a type="button" onclick="cancel()" class="btn btn-default float-right">Закрыть</a>
                        </div>                <!-- /.card -->
                    </div>
                </form>
            </div>
            <div id="print_Panel" class="container-fluid" style="height:100px;">
                <div id="reportPanel" class="card card-primary card-outline card-tabs">
                    <div class="card-header p-1 pt-1 ">
                        <div class="dt-buttons btn-group flex-wrap">
                            <!--<button class="btn btn-secondary buttons-excel buttons-html5" tabindex="0" aria-controls="example1" type="button"><span>Excel</span></button>
                            <button class="btn btn-secondary buttons-pdf buttons-html5" tabindex="0" aria-controls="example1" type="button"><span>PDF</span></button>
                            <a class="btn btn-secondary buttons-print" onClick="javascript:CallPrint('print_Panel');" tabindex="0" aria-controls="example1" type="button"><span>Печать</span></a>-->
                        </div>
                    </div>
                    <div id="reportPanelBody" class="card-body">
                        <div class="alert alert-warning alert-dismissible" style="max-width:450px;">
                            <!--<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>-->
                            <h5><i class="icon fas fa-exclamation-triangle"></i> </h5>
                            Отчет не сформирован. Нажмите "Сформировать" для получения отчета
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
            </div>


        </section>


        {% endblock %}

        {% block script_footer %}
        <script src="{% static 'js/gauge.min.js' %}?ver={% settings_value 'APP_VER' %}"></script>
        <script src="{% static 'js/speedometer.js' %}?ver={% settings_value 'APP_VER' %}"></script>
        <!-- date-range-picker -->
        <script src="{% static 'lte/plugins/daterangepicker/daterangepicker.js' %}?ver={% settings_value 'APP_VER' %}"></script>
        <script>
            $(function () {
                $('.date').datetimepicker({
                    locale: 'ru',
                    format: 'L',
                    format: 'DD.MM.YYYY',
                    autoclose: true,
                });
                //Initialize Select2 Elements
                $('.select2').select2({
                    theme: 'bootstrap4'
                })

            });
            function reportshow() {
                $("#reportPanelBody").html('<div class="overlay"><i class= "fas fa-2x fa-sync-alt" ></i></div>')

                var DataStart = $("#id_datestart").val();
                var DataStop = $("#id_datestop").val();
                var id_block = $("#id_block").select2('data');
                console.log(id_block[0].id)
                if (!!DataStart) {
                    $.ajax({
                        type: 'POST', // метод отправки
                        url: window.location.pathname,
                        data: {
                            "DataStart": DataStart,
                            "DataStop": DataStop,
                            "metod": 'create',
                            "id_block": id_block[0].id,
                        },
                        success: function (data) {
                            document.getElementById('reportPanel').style.height = '';
                            $("#reportPanelBody").html(data); // при успешном получении ответа от сервера, заносим полученные данные в элемент с классом answer
                        },
                        error: function (dataerr) {
                            $("#reportPanelBody").html(dataerr); // при успешном получении ответа от сервера, заносим полученные данные в элемент с классом answer

                        }
                    });

                }

            }
            function cancel() {
                document.location.href = "../";
            }

           function CallPrint(strid) {
			   var prtContent = document.getElementById(strid);
			   var WinPrint = window.open('', '', 'left=50,top=50,width=800,height=640,toolbar=0,scrollbars=1,status=0');
			   WinPrint.document.write('');
			   WinPrint.document.write(prtContent.innerHTML);
			   WinPrint.document.write('');
			   WinPrint.document.close();
			   WinPrint.focus();
			   WinPrint.print();
			   WinPrint.close();
			   prtContent.innerHTML = strOldOne;
}
        
        </script>
        {% endblock script_footer %}