apps/eps/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.conf.urls import include # Используйте include() чтобы добавлять URL из каталога приложения

from apps.eps.views import views_eps

urlpatterns = [
    url(r'^$', views_eps.main_index, name='main_index'),
    url(r'^map/$', views_eps.map, name='map'),
    #№url(r'sensor_ajax/$', views_acs.sensor_ajax, name='sensor_ajax'),
    url(r'ajax/$', views_eps.get_ajax, name='get_ajax'),
    url(r'gettag/$', views_eps.get_tag, name='get_tag'),
    
    
    ]

mfss/urls.py
# -*- coding: utf-8 -*-
from django.contrib import admin
from django.conf.urls import url
from django.conf.urls import include # Используйте include() чтобы добавлять URL из каталога приложения
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings
from . import views



urlpatterns = [

    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/img/favicon.ico'), name='favicon'),
    url(r'^$', RedirectView.as_view(url='/main/', permanent=True)), #Перенаправляет все запросы 
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('apps.main.urls')),
    url(r'^acs/', include('apps.acs.urls')),
    url(r'^fps/', include('apps.fps.urls')),
    url(r'^dcs/', include('apps.dcs.urls')),
    url(r'^eps/', include('apps.eps.urls')),
    url(r'^fp/', include('apps.fp.urls')),
    url(r'^ktp/', include('apps.ktp.urls')),
    url(r'^scada/', include('apps.scada.urls')),
    url(r'^block/', include('apps.block.urls')),
    url(r'^management/', include('apps.management.urls')),
    url(r'^api/v1/', include('api.v1.urls')),

    url(r'^accounts/logout/', views.user_logout, name='user_logout'),
    url(r'^accounts/', views.user_login, name='user_login'),

    url('bot/', include('tgbot.urls')),
]

urlpatterns += static(settings.DOWNLOAD_URL, document_root=settings.DOWNLOAD_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/eps/models/model_anchors.py
# -*- coding: utf-8 -*-
from datetime import datetime

from django.db import models

class Anchors(models.Model):  # Анкера
    """
    Модель справочника Анкеров
    """
    rls_id = models.CharField(max_length=160,
        help_text="",
        default=" ",
        verbose_name="id rls")
    sn = models.CharField(max_length=60,
        help_text="",
        default=" ",
        verbose_name="Серийный номер")
    origin = models.CharField(max_length=100,
        help_text="",
        default=" ",
        verbose_name="origin")
    disabled = models.BooleanField(blank=False,
                                   default=False,
                                   verbose_name="disabled")
    descr = models.CharField(max_length=100,
        help_text="",
        default=" ",
        verbose_name="descr")
    label = models.CharField(max_length=100,
        help_text="",
        default=" ",
        verbose_name="label")
    x = models.FloatField(default=0.0,
        help_text="",
        verbose_name="x")
    y = models.FloatField(default=0.0,
        help_text="",
        verbose_name="y")
    z = models.FloatField(default=0.0,
        help_text="",
        verbose_name="z")
    device_type = models.CharField(max_length=50,
        help_text="",
        default=" ",
        verbose_name="device_type")
    status = models.CharField(max_length=20,
        help_text="",
        default=" ",
        verbose_name="status")
    ip_address = models.CharField(max_length=20,
        help_text="",
        default=" ",
        verbose_name="ip_address")
    coap_resource = models.CharField(max_length=20,
        help_text="",
        default=" ",
        verbose_name="coap_resource")
    subscribed = models.BooleanField(blank=False,
                                   default=False,
                                   verbose_name="subscribed")
    message_time = models.DateTimeField(auto_now=False,
        auto_now_add=False,
        blank=True,
        verbose_name="message_time")
    status_time = models.DateTimeField(auto_now=False,
        auto_now_add=False,
        blank=True,
        verbose_name="status_time")
    total_packets = models.IntegerField(default=0)
    invalid_packets = models.IntegerField(default=0)
  
    def getId(self):
        return self.id

    def __str__(self):
        return self.label

    class Meta:   # отображение в админики
        ordering = ('label',)
        verbose_name = u'анкер'
        verbose_name_plural = u'анкера'
        indexes = [models.Index(fields=['label',]),]

apps/eps/models/model_tagdates.py
# -*- coding: utf-8 -*-
from django.db import models
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
from .model_tags import Tag

class TagDate(models.Model):  # Отметки
    """
    Модель отметок датчика
    """
    tag = models.ForeignKey(
        Tag,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="Датчик")
    time = models.DateTimeField(
        auto_now=False,
        auto_now_add=False,
        blank=True,
        verbose_name="Время отметки")
    accuracy = models.IntegerField(default=0)
    kinematic = models.IntegerField(default=0)
    seq = models.IntegerField(default=0)
    source = models.CharField(
        max_length=60,
        help_text="",
        default=" ",
        verbose_name="source")
    le_status = models.CharField(
        max_length=60,
        help_text="",
        default=" ",
        verbose_name="Статус")
    motion = models.CharField(
        max_length=60,
        help_text="",
        default=" ",
        verbose_name="motion")
    solution = models.CharField(
        max_length=60,
        help_text="",
        default=" ",
        verbose_name="solution")
    x = models.FloatField(default=0.0,
        help_text="",
        verbose_name="x")
    y = models.FloatField(default=0.0,
        help_text="",
        verbose_name="y")
    z = models.FloatField(default=0.0,
        help_text="",
        verbose_name="z")
    
    class Meta:   # отображение в админики
        unique_together = ('tag','time',)
        verbose_name = u'отметка'
        verbose_name_plural = u'отметки'
        indexes = [
            models.Index(fields=['tag',]),
            ]

apps/eps/models/model_tags.py
# -*- coding: utf-8 -*-
from datetime import datetime

from django.db import models

class Tag(models.Model):  # Датчики
    critical_type_list = (('max', 'Максимальный'),
        ('min', 'Минимальный'),)

    """
    Модель справочника датчиков
    """
    name = models.CharField(max_length=160,
        help_text="",
        default=" ",
        verbose_name="Наименование")
    sn = models.CharField(max_length=60,
        help_text="",
        default=" ",
        verbose_name="Серийный номер")
    descr = models.CharField(max_length=100,
        help_text="",
        default=" ",
        verbose_name="descr")
    origin = models.CharField(max_length=100,
        help_text="",
        default=" ",
        verbose_name="origin")
    le_status = models.CharField(
        max_length=60,
        help_text="",
        default=" ",
        verbose_name="Статус")
    x = models.FloatField(default=0.0,
        help_text="",
        verbose_name="x")
    y = models.FloatField(default=0.0,
        help_text="",
        verbose_name="y")
    z = models.FloatField(default=0.0,
        help_text="",
        verbose_name="z")
  
    def getId(self):
        return self.id

    def __str__(self):
        return self.name

    class Meta:   # отображение в админики
        ordering = ('name',)
        verbose_name = u'датчик'
        verbose_name_plural = u'датчики'
        indexes = [models.Index(fields=['name',]),
            ]

apps/eps/views/views_eps.py
# -*- coding: utf-8 -*-
import traceback
import requests
import random

from PIL import Image
import numpy as np


from datetime import datetime,timedelta
from requests.auth import HTTPBasicAuth
from django.conf import settings
from django.db.models import Q
from django.shortcuts import render
from django.http import HttpResponse
from django.conf import settings
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.db.models import Avg, Max, Min

from apps.eps.models.model_tags import Tag
from apps.eps.models.model_tagdates import TagDate

from apps.util import generalmodule
from sabron.util import logging


def get_ajax(request):
    try:
        if request.method == "POST":
            #img = Image.open(settings.BASE_DIR+'/static/img//plan/inver/otm_102_zone.png')
            #x,y= img.size
            #mas = np.eye(x, y)
            #for xx in range(0,x):
            #    for yy in range(0,y):
            #        p = img.getpixel((xx,yy))
            #        if p[1]!=0:
            #           mas[xx][yy] = 1
            #       else:
            #            mas[xx][yy] = 0

            #r=requests.get("https://87.103.198.150:56443/CFG-API/monitor/tags",auth=HTTPBasicAuth('system', 'admin'), verify=False)
            r=requests.get("https://192.168.10.5/CFG-API/monitor/tags",auth=HTTPBasicAuth('system', 'admin'), verify=False)
            if r.status_code!=200:
                return
            mystr=r.json()
            m_sensor = []
            for tag in mystr['items']:
                x = int(int(tag['x'])*22)
                y =770 - int(int(tag['y'])*22)
                ds = int(settings.MAS[x][y])
                if ds==0:
                    continue
                tag_dict = dict()
                tag_dict.update(id=tag['sn'])
                tag_dict.update(name=str(tag['sn']))
                tag_dict.update(sn=str(tag['sn']))
                #tag_dict.update(le_status=tag.le_status)
                tag_dict.update(x=x)
                tag_dict.update(y=y)
                tag_dict.update(z=int(tag['z']))
                m_sensor.append(tag_dict)
            return generalmodule.ReturnJson(200,m_sensor)

        if request.method == "GET":
            img = Image.open(settings.BASE_DIR+'/static/img//plan/inver/otm_102_zone.png')
            x,y= img.size
            mas = np.eye(x, y)
            for xx in range(0,x):
                for yy in range(0,y):
                    p = img.getpixel((xx,yy))
                    if p[1]!=0:
                        mas[xx][yy] = 1
                    else:
                        mas[xx][yy] = 0
            Tag_list = Tag.objects.filter(le_status ='HEALTH').all().order_by('name')
            m_sensor = []
            for tag in Tag_list:
                #x = (int(tag.x)+random.randint(1,5))*(1014 / 42)
                #y =829 - (int(tag.y)+random.randint(1,5))*(1014/42)
                x = int(int(tag.x)*22)
                #y =792 - int(int(tag.y)*22)
                y =770 - int(int(tag.y)*22)
                ds = int(mas[x][y])
                if ds==0:
                    continue
                tag_dict = dict()
                tag_dict.update(id=tag.id)
                tag_dict.update(name=tag.name)
                tag_dict.update(sn=tag.sn)
                tag_dict.update(le_status=tag.le_status)
                #tag_dict.update(x=int(tag.x))
                #tag_dict.update(y=int(tag.y))
                tag_dict.update(x=x)
                tag_dict.update(y=y)
                tag_dict.update(z=int(tag.z))
                m_sensor.append(tag_dict)
            
            return generalmodule.ReturnJson(200,m_sensor)
    except Exception as err:
        logging.error(traceback.format_exc())
        data = dict()
        data.update(status=-1)
        return generalmodule.ReturnJson(200,data)

def get_tag(request):
    try:
        if request.method == "POST":
            #r=requests.get("https://87.103.198.150:56443/CFG-API/monitor/tags",auth=HTTPBasicAuth('system', 'admin'), verify=False)
            r=requests.get("https://192.168.10.5/CFG-API/monitor/tags",auth=HTTPBasicAuth('system', 'admin'), verify=False)
            if r.status_code!=200:
                return
            mystr=r.json()
            m_sensor = []
            for tag in mystr['items']:
                x = int(int(tag['x'])*22)
                y =770 - int(int(tag['y'])*22)
                tag_dict = dict()
                tag_dict.update(id=tag['sn'])
                tag_dict.update(name=str(tag['sn']))
                tag_dict.update(sn=str(tag['sn']))
                #tag_dict.update(le_status=tag.le_status)
                tag_dict.update(x=int(x))
                tag_dict.update(y=int(y))
                tag_dict.update(z=int(tag['z']))
                m_sensor.append(tag_dict)
            #Tag_list = Tag.objects.filter(le_status ='HEALTH').all().order_by('name')
            #m_sensor = []
            #for tag in Tag_list:
            #    tag_dict = dict()
            #    tag_dict.update(id=tag.id)
            #    tag_dict.update(name=tag.name)
            #    tag_dict.update(sn=tag.sn)
            #    tag_dict.update(le_status=tag.le_status)
            #    tag_dict.update(x=int(tag.x))
            #    tag_dict.update(y=int(tag.y))
            #    tag_dict.update(z=int(tag.z))
            #    m_sensor.append(tag_dict)
            return generalmodule.ReturnJson(200,m_sensor)
        if request.method == "GET":
            Tag_list = Tag.objects.filter(le_status ='HEALTH').all().order_by('name')
            m_sensor = []
            for tag in Tag_list:
                tag_dict = dict()
                tag_dict.update(id=tag.id)
                tag_dict.update(name=tag.name)
                tag_dict.update(sn=tag.sn)
                tag_dict.update(le_status=tag.le_status)
                tag_dict.update(x=int(tag.x))
                tag_dict.update(y=int(tag.y))
                tag_dict.update(z=int(tag.z))
                m_sensor.append(tag_dict)
            return generalmodule.ReturnJson(200,m_sensor)
    except Exception as err:
        logging.error(traceback.format_exc())
        data = dict()
        data.update(status=-1)
        return generalmodule.ReturnJson(200,data)

def main_index_default(request):
     if request.method == "GET":
        context = {
                   }
        return render(request, 'eps_main.html',context) 


def map(request):
     if request.method == "GET":
        tag_list = Tag.objects.all().order_by('name')
        context = {
                    'tag_list':tag_list,
                   }
        return render(request, 'eps_map.html',context) 

@login_required(login_url='/accounts/login/?next=')
@never_cache
def main_index(request):
    try:
        return main_index_default(request)
    except Exception as err:
        logging.error(traceback.format_exc())
 

apps/eps/templates/eps_map.html
{% extends "subsystem_eps.html" %}
{% load static %}
{% load mysettings %}


{% block header_link %}
<link type="text/css" rel="stylesheet" href="{% static '/css/speedometer.css' %}?ver={% settings_value 'APP_VER' %}">
{% endblock header_link %}

{% block info_title %}
<h5>
    Система определения местоположения сотрудников фабрики <h5>
    {% endblock info_title %}

    {% block content %}
    <section class="content-header">
        <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Отм. +10,200</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/eps/">Главная</a></li>
                    <li class="breadcrumb-item active">Отм. +10,200</li>
                </ol>
            </div>
        </div>
        </div><!-- /.container-fluid -->
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="card card-primary card-outline direct-chat">
                <div class="card-header">
                    <!--<div class="card-tools">
                        <button type="button" class="btn btn-tool" id="#optionsZone" onclick="edit_zone(this.id); return false">
                            <i class="fa-sharp fa-solid fa-screwdriver-wrench" style="color: blue;"></i> Добавить опасную зону
                        </button>
                        <button type="button" class="btn btn-tool" id="#personsOnMap" onclick="persons(this.id); return false">
                            <i class="fa-solid fa-users" style="color: blue;"></i> Персонал
                        </button>
                        <button type="button" class="btn btn-tool" id="#zoneOnMap" onclick="persons(this.id); return false">
                            <i class="fa-sharp fa-solid fa-triangle-exclamation" style="color: red;"></i> Опасные зоны
                        </button>
                    </div>-->
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12 col-md-12 col-lg-12 order-2 order-md-1" style="padding: 10px 25px 15px">
                            <div class="d-md-flex">
                                <div class="p-1 flex-fill" style="overflow: hidden">
                                    <canvas id="canvas" style="border: 1px solid black"></canvas>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}
    {% block script_footer %}
    <script src="https://rawgit.com/kangax/fabric.js/master/dist/fabric.js"></script>
    <script src="{% static 'js/map.js' %}?ver={% settings_value 'APP_VER' %}"></script>
    {% endblock script_footer %}

apps/eps/templates/eps_map_canvas.html
{% extends "subsystem_eps.html" %}
{% load static %}
{% load mysettings %}


{% block header_link %}
<link type="text/css" rel="stylesheet" href="{% static '/css/speedometer.css' %}?ver={% settings_value 'APP_VER' %}">
{% endblock header_link %}

{% block info_title %}
<h5>
    Система определения местоположения сотрудников фабрики <h5>
    {% endblock info_title %}

    {% block content %}
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <p id="id_time"></p>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="card card-primary card-outline direct-chat">
                <div class="card-header">
                    <!--<div class="card-tools">
                        <button type="button" class="btn btn-tool" id="#optionsZone" onclick="edit_zone(this.id); return false">
                            <i class="fa-sharp fa-solid fa-screwdriver-wrench" style="color: blue;"></i> Добавить опасную зону
                        </button>
                        <button type="button" class="btn btn-tool" id="#personsOnMap" onclick="persons(this.id); return false">
                            <i class="fa-solid fa-users" style="color: blue;"></i> Персонал
                        </button>
                        <button type="button" class="btn btn-tool" id="#zoneOnMap" onclick="persons(this.id); return false">
                            <i class="fa-sharp fa-solid fa-triangle-exclamation" style="color: red;"></i> Опасные зоны
                        </button>
                    </div>-->
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12 col-md-12 col-lg-12 order-2 order-md-1" style="padding: 10px 25px 15px">
                            <div class="d-md-flex">
                                <div class="p-1 flex-fill" style="overflow: hidden">
                                    <canvas id='myCanvas' width='900' height='700'></canvas>
                                    <canvas id='kopi' width='900' height='700'></canvas>
                                    <canvas id='canvas' width='40' height='50'></canvas>
                                    <img id='im'  style='display:none;'>
                                    <div id='inf'>0</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}
    {% block script_footer %}
    <script src="https://rawgit.com/kangax/fabric.js/master/dist/fabric.js"></script>

    <script>
 var и=document.all;
	const image = new Image();
	//image.src = 'http://127.0.0.1:8787/static/img/plan/otm_102.png';
	image.src = '{% static 'img/plan/otm_102.png' %}';
	image.crossOrigin = "Anonymous";

	var ne=0;   
	image.onload=function(){    
			var canvas=document.getElementById('myCanvas');
			var ctx = canvas.getContext('2d');
			    ctx.drawImage(image,0,0,900,700);
 
			var canvas2 = document.getElementById('canvas');
			var ct = canvas2.getContext('2d');
			tat=ct.getImageData(0,0,40,50);
			var pux=tat.data; //массив пикселей объекта передвижения
			tot=ctx.getImageData(40,470,40,50);
			pix=tot.data;//массив пикселей объекта на картинке передвижения
			for(s=0,d=50;s<d;s+=1){
				var o=0;
				for(n=s*160, m=(s*160)+160; n<m; n+=4){
					pux[n]=pix[n]; pux[n+1]=pix[n+1];pux[n+2]=pix[n+2]; pux[n+3]=255;
					if((pix[n]==82)&&( pix[n+1]=89)&&(pix[n+2]=66)){pux[n+3]=0;}
					pix[n]=82; pix[n+1]=89; pix[n+2]=66;//копирую оюъект с картинки и закрашиваю на рисунке его место.
					}
			}
	ct.putImageData(tat, 0, 0);
	ctx.putImageData(tot, 40, 470);
	var can=document.getElementById('kopi');
	var cx = can.getContext('2d');
	    cx.drawImage(и.myCanvas,0,0,900,700);
	и.kopi.style.display='none'
	}

и.myCanvas.onmousemove=function(evt){
    
	var canvas=document.getElementById('myCanvas');
	var ctx = myCanvas.getContext('2d');
	trt=ctx.getImageData(0,0,900,700);

	pax=trt.data;
	y=evt.clientY-30;
	x=evt.clientX-25;
    console.log(x+" : "+y) 
    mm=ctx.getImageData(evt.clientX,evt.clientY,1,1);
    console.log(mm)
    red=mm.data[0];
    green=mm.data[1];
    blue=mm.data[2];
    alpha=mm.data[3];
    console.log(red)
    console.log(green)
    console.log(blue)
    console.log(alpha)
	if(ne==1){
		и.myCanvas.width=и.myCanvas.width;
		ctx.drawImage(и.kopi,0,0,900,700);
		var t=0;
		var u1=x*4+y*900*4;//левый верхний угол объекта
		if((pax[u1-4]==82)&&( pax[u1-3]=89)&&(pax[u1-2]=66))
			{t++;}
		else
			{ne=0; x+=20;y+=20; }
		var u2=(x+40)*4+(y+50)*900*4;//нижний правый
		    if((pax[u2+4]==82)&&( pax[u2+5]=89)&&(pax[u2+6]=66)){t++;}else{ne=0; x-=20; y-=20; }
		var u3=(x+40)*4+y*900*4;//верхний правый
		    if((pax[u3+4]==82)&&( pax[u3+5]=89)&&(pax[u3+6]=66)){t++;}else{ne=0; x-=20;y+=20;}
		    if(t<2){x=390;y=500;}
		     и.inf.innerHTML=x+'--'+y+'--'+t;
		ctx.drawImage(и.canvas,x,y,40,50);
	}
}   
onmouseup=function(){ne=0}  
onmousedown=function(){ne=1}


    </script>
    {% endblock script_footer %}